conditions_map = {
    "Chance Light Rain": ["wi-day-showers", "wi-night-alt-showers"],
    "Chance Light Snow": [],
    "Chance Rain And Snow": [],
    "Chance Rain And Snow Showers": ["wi-day-rain-mix", "wi-night-alt-rain-mix"],
    "Chance Rain Showers": ["wi-day-showers", "wi-night-alt-showers"],
    "Chance Showers And Thunderstorms": [],
    "Chance Snow Showers": [],
    "Clear": ["wi-stars"],
    "Cloudy": ["wi-cloudy"],
    "Drizzle Likely": [],
    "Haze": ["wi-day-haze", "wi-night-fog"],
    "Isolated Rain Showers": ["wi-day-showers", "wi-night-alt-showers"],
    "Light Rain": [],
    "Light Rain Likely": [],
    "Light Snow": [],
    "Light Snow Likely": [],
    "Mostly Clear": [],
    "Mostly Cloudy": ["wi-day-cloudy", "wi-night-alt-cloudy"],
    "Mostly Sunny": ["wi-day-sunny-overcast"],
    "Partly Cloudy": [],
    "Partly Sunny": [],
    "Patchy Fog": [],
    "Rain": [],
    "Rain Likely": [],
    "Rain Showers": ["wi-day-showers", "wi-night-alt-showers"],
    "Rain Showers Likely": ["wi-day-showers", "wi-night-alt-showers"],
    "Scattered Rain Showers": ["wi-day-showers", "wi-night-alt-showers"],
    "Showers And Thunderstorms": "",
    "Showers And Thunderstorms Likely": "",
    "Slight Chance Light Rain": "",
    "Slight Chance Light Snow": "",
    "Slight Chance Rain And Snow Showers": "",
    "Slight Chance Rain Showers": "",
    "Slight Chance Showers And Thunderstorms": "",
    "Slight Chance Snow Showers": "",
    "Snow Showers": "",
    "Snow Showers Likely": [],
    "Sunny": ["wi-day-sunny"],
}
