conditions_map = {
    "Chance Light Rain": ["wi-day-showers", "wi-night-alt-showers"],
    "Chance Light Snow": ["wi-day-snow", "wi-night-alt-snow"],
    "Chance Rain And Snow": ["wi-day-rain-mix", "wi-night-alt-rain-mix"],
    "Chance Rain And Snow Showers": ["wi-day-rain-mix", "wi-night-alt-rain-mix"],
    "Chance Rain Showers": ["wi-day-showers", "wi-night-alt-showers"],
    "Chance Showers And Thunderstorms": ["", ""],
    "Chance Snow Showers": ["wi-day-snow", "wi-night-alt-snow"],
    "Clear": ["wi-stars"],
    "Cloudy": ["wi-cloudy"],
    "Drizzle Likely": ["wi-day-showers", "wi-night-alt-showers"],
    "Haze": ["wi-day-haze", "wi-night-fog"],
    "Isolated Rain Showers": ["wi-day-showers", "wi-night-alt-showers"],
    "Light Rain": ["wi-day-rain", "wi-night-alt-rain"],
    "Light Rain Likely": ["wi-day-rain", "wi-night-alt-rain"],
    "Light Snow": ["wi-day-snow", "wi-night-alt-snow"],
    "Light Snow Likely": ["wi-day-snow", "wi-night-alt-snow"],
    "Mostly Clear": ["wi-night-alt-partly-cloudy"],
    "Mostly Cloudy": ["wi-day-cloudy", "wi-night-alt-cloudy"],
    "Mostly Sunny": ["wi-day-sunny-overcast"],
    "Partly Cloudy": ["wi-day-sunny-overcast", "wi-night-alt-partly-cloudy"],
    "Partly Sunny": ["wi-day-cloudy-high"],
    "Patchy Fog": ["wi-day-fog", "wi-night-fog"],
    "Rain": ["wi-day-rain", "wi-night-alt-rain"],
    "Rain Likely": ["wi-day-rain", "wi-night-alt-rain"],
    "Rain Showers": ["wi-day-showers", "wi-night-alt-showers"],
    "Rain Showers Likely": ["wi-day-showers", "wi-night-alt-showers"],
    "Scattered Rain Showers": ["wi-day-showers", "wi-night-alt-showers"],
    "Showers And Thunderstorms": ["wi-day-storm-showers", "wi-night-alt-storm-showers"],
    "Showers And Thunderstorms Likely": [
        "wi-day-storm-showers",
        "wi-night-alt-storm-showers",
    ],
    "Slight Chance Light Rain": ["wi-day-rain", "wi-night-alt-rain"],
    "Slight Chance Light Snow": ["wi-day-snow", "wi-night-alt-snow"],
    "Slight Chance Rain And Snow Showers": ["wi-day-rain-mix", "wi-night-alt-rain-mix"],
    "Slight Chance Rain Showers": ["wi-day-rain", "wi-night-alt-rain"],
    "Slight Chance Showers And Thunderstorms": [
        "wi-day-storm-showers",
        "wi-night-alt-storm-showers",
    ],
    "Slight Chance Snow Showers": ["wi-day-snow", "wi-night-alt-snow"],
    "Snow": ["wi-day-snow", "wi-night-alt-snow"],
    "Snow Likely": ["wi-day-snow", "wi-night-alt-snow"],
    "Snow Showers": ["wi-day-snow", "wi-night-alt-snow"],
    "Snow Showers Likely": ["wi-day-snow", "wi-night-alt-snow"],
    "Sunny": ["wi-day-sunny"],
}
