forecast = [
    {
        "number": 1,
        "name": "Overnight",
        "startTime": "2023-12-19T01:00:00-06:00",
        "endTime": "2023-12-19T06:00:00-06:00",
        "isDaytime": False,
        "temperature": 16,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": -10.555555555555555},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 80},
        "windSpeed": "3 mph",
        "windDirection": "W",
        "icon": "https://api.weather.gov/icons/land/night/skc?size=medium",
        "shortForecast": "Clear",
        "detailedForecast": "Clear, with a low around 16. West wind around 3 mph.",
    },
    {
        "number": 2,
        "name": "Tuesday",
        "startTime": "2023-12-19T06:00:00-06:00",
        "endTime": "2023-12-19T18:00:00-06:00",
        "isDaytime": True,
        "temperature": 38,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": -9.444444444444445},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 84},
        "windSpeed": "3 to 13 mph",
        "windDirection": "S",
        "icon": "https://api.weather.gov/icons/land/day/sct?size=medium",
        "shortForecast": "Mostly Sunny",
        "detailedForecast": "Mostly sunny, with a high near 38. South wind 3 to 13 mph, with gusts as high as 22 mph.",
    },
    {
        "number": 3,
        "name": "Tuesday Night",
        "startTime": "2023-12-19T18:00:00-06:00",
        "endTime": "2023-12-20T06:00:00-06:00",
        "isDaytime": False,
        "temperature": 29,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": -7.222222222222222},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 66},
        "windSpeed": "12 to 15 mph",
        "windDirection": "S",
        "icon": "https://api.weather.gov/icons/land/night/sct?size=medium",
        "shortForecast": "Partly Cloudy",
        "detailedForecast": "Partly cloudy, with a low around 29. South wind 12 to 15 mph, with gusts as high as 24 mph.",
    },
    {
        "number": 4,
        "name": "Wednesday",
        "startTime": "2023-12-20T06:00:00-06:00",
        "endTime": "2023-12-20T18:00:00-06:00",
        "isDaytime": True,
        "temperature": 48,
        "temperatureUnit": "F",
        "temperatureTrend": "falling",
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": -1.1111111111111112},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 63},
        "windSpeed": "7 to 12 mph",
        "windDirection": "S",
        "icon": "https://api.weather.gov/icons/land/day/sct?size=medium",
        "shortForecast": "Mostly Sunny",
        "detailedForecast": "Mostly sunny. High near 48, with temperatures falling to around 43 in the afternoon. South wind 7 to 12 mph, with gusts as high as 20 mph.",
    },
    {
        "number": 5,
        "name": "Wednesday Night",
        "startTime": "2023-12-20T18:00:00-06:00",
        "endTime": "2023-12-21T06:00:00-06:00",
        "isDaytime": False,
        "temperature": 35,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": -0.5555555555555556},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 79},
        "windSpeed": "9 mph",
        "windDirection": "SSE",
        "icon": "https://api.weather.gov/icons/land/night/ovc?size=medium",
        "shortForecast": "Cloudy",
        "detailedForecast": "Cloudy, with a low around 35. South southeast wind around 9 mph.",
    },
    {
        "number": 6,
        "name": "Thursday",
        "startTime": "2023-12-21T06:00:00-06:00",
        "endTime": "2023-12-21T18:00:00-06:00",
        "isDaytime": True,
        "temperature": 48,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 3.3333333333333335},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 79},
        "windSpeed": "7 to 10 mph",
        "windDirection": "SSE",
        "icon": "https://api.weather.gov/icons/land/day/bkn/rain?size=medium",
        "shortForecast": "Mostly Cloudy then Slight Chance Light Rain",
        "detailedForecast": "A slight chance of rain after noon. Mostly cloudy, with a high near 48. South southeast wind 7 to 10 mph.",
    },
    {
        "number": 7,
        "name": "Thursday Night",
        "startTime": "2023-12-21T18:00:00-06:00",
        "endTime": "2023-12-22T06:00:00-06:00",
        "isDaytime": False,
        "temperature": 40,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": 70},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 5},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 96},
        "windSpeed": "10 mph",
        "windDirection": "SSE",
        "icon": "https://api.weather.gov/icons/land/night/rain,60/rain,70?size=medium",
        "shortForecast": "Light Rain Likely",
        "detailedForecast": "Rain likely. Cloudy, with a low around 40. South southeast wind around 10 mph. Chance of precipitation is 70%. New rainfall amounts between a tenth and quarter of an inch possible.",
    },
    {
        "number": 8,
        "name": "Friday",
        "startTime": "2023-12-22T06:00:00-06:00",
        "endTime": "2023-12-22T18:00:00-06:00",
        "isDaytime": True,
        "temperature": 50,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": 50},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 8.333333333333334},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 100},
        "windSpeed": "10 mph",
        "windDirection": "S",
        "icon": "https://api.weather.gov/icons/land/day/rain,50?size=medium",
        "shortForecast": "Chance Light Rain",
        "detailedForecast": "A chance of rain. Cloudy, with a high near 50. Chance of precipitation is 50%.",
    },
    {
        "number": 9,
        "name": "Friday Night",
        "startTime": "2023-12-22T18:00:00-06:00",
        "endTime": "2023-12-23T06:00:00-06:00",
        "isDaytime": False,
        "temperature": 44,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": 40},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 7.777777777777778},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 100},
        "windSpeed": "8 mph",
        "windDirection": "SSE",
        "icon": "https://api.weather.gov/icons/land/night/rain,40/rain?size=medium",
        "shortForecast": "Chance Light Rain",
        "detailedForecast": "A chance of rain. Cloudy, with a low around 44. Chance of precipitation is 40%.",
    },
    {
        "number": 10,
        "name": "Saturday",
        "startTime": "2023-12-23T06:00:00-06:00",
        "endTime": "2023-12-23T18:00:00-06:00",
        "isDaytime": True,
        "temperature": 53,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 9.444444444444445},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 100},
        "windSpeed": "9 mph",
        "windDirection": "SSE",
        "icon": "https://api.weather.gov/icons/land/day/bkn?size=medium",
        "shortForecast": "Mostly Cloudy",
        "detailedForecast": "Mostly cloudy, with a high near 53.",
    },
    {
        "number": 11,
        "name": "Saturday Night",
        "startTime": "2023-12-23T18:00:00-06:00",
        "endTime": "2023-12-24T06:00:00-06:00",
        "isDaytime": False,
        "temperature": 44,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 8.88888888888889},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 100},
        "windSpeed": "8 to 12 mph",
        "windDirection": "SE",
        "icon": "https://api.weather.gov/icons/land/night/rain?size=medium",
        "shortForecast": "Chance Light Rain",
        "detailedForecast": "A chance of rain. Mostly cloudy, with a low around 44.",
    },
    {
        "number": 12,
        "name": "Sunday",
        "startTime": "2023-12-24T06:00:00-06:00",
        "endTime": "2023-12-24T18:00:00-06:00",
        "isDaytime": True,
        "temperature": 54,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 8.88888888888889},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 100},
        "windSpeed": "12 to 15 mph",
        "windDirection": "SE",
        "icon": "https://api.weather.gov/icons/land/day/rain?size=medium",
        "shortForecast": "Chance Light Rain",
        "detailedForecast": "A chance of rain. Mostly cloudy, with a high near 54.",
    },
    {
        "number": 13,
        "name": "Sunday Night",
        "startTime": "2023-12-24T18:00:00-06:00",
        "endTime": "2023-12-25T06:00:00-06:00",
        "isDaytime": False,
        "temperature": 47,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 8.88888888888889},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 100},
        "windSpeed": "16 mph",
        "windDirection": "SE",
        "icon": "https://api.weather.gov/icons/land/night/rain?size=medium",
        "shortForecast": "Light Rain Likely",
        "detailedForecast": "Rain likely. Cloudy, with a low around 47.",
    },
    {
        "number": 14,
        "name": "Christmas Day",
        "startTime": "2023-12-25T06:00:00-06:00",
        "endTime": "2023-12-25T18:00:00-06:00",
        "isDaytime": True,
        "temperature": 55,
        "temperatureUnit": "F",
        "temperatureTrend": None,
        "probabilityOfPrecipitation": {"unitCode": "wmoUnit:percent", "value": None},
        "dewpoint": {"unitCode": "wmoUnit:degC", "value": 10},
        "relativeHumidity": {"unitCode": "wmoUnit:percent", "value": 96},
        "windSpeed": "15 mph",
        "windDirection": "SSE",
        "icon": "https://api.weather.gov/icons/land/day/rain?size=medium",
        "shortForecast": "Light Rain Likely",
        "detailedForecast": "Rain likely. Mostly cloudy, with a high near 55.",
    },
]
